//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingGo.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Product
    {
        [Display(Name = "商品編號")]
        public int Id { get; set; }
        [Display(Name = "商品名稱")]
        public string Name { get; set; }
        [Display(Name = "商品描述")]
        public string Description { get; set; }
        [Display(Name = "商品分類編號")]
        public int CategoryId { get; set; }
        [Display(Name = "商品價格")]
        public decimal Price { get; set; }
        [Display(Name = "商品生效日")]
        public Nullable<System.DateTime> PublishDate { get; set; }
        [Display(Name = "商品狀態")]
        public Nullable<bool> Status { get; set; }
        [Display(Name = "商品圖片連結名稱")]
        public string DefaultImageURL { get; set; }
        [Display(Name = "商品庫存量")]
        public int Quantity { get; set; }
    }
}
